### PR TITLE
Devel fixbc

### PR DESCRIPTION
**Pull request by be-green**
* Fix hyper = T so that it works
* Pooled estimate at the bottom
* Tests within each model type, more comprehensive, that cover running, plotting & printing for cases where models are pre-specified, data is given and pooling is compared, data is given and prior is compared
* Fixed weird bug that had to do with names getting destroyed by factors

### CODE REVIEW

**Comment by wwiecek** [comment]
Hey Brice, please don't commit the large PDF file. Can you remove that (and ignore for future commits?).
Not sure why your latest commit didn't trigger Travis -- or if it did, it is still failing checks? https://travis-ci.org/wwiecek/baggr/pull_requests

**Comment by be-green** [comment]
Yeah, not sure how that got in there...

**Comment by wwiecek** [comment]
Ah, great, Travis is now checking your latest commit, so we will know soon. If it passes, I will merge. Thanks a bunch on such prompt edits!

**Comment by be-green** [comment]
Of course, for once I actually had a few hours to get some work done! Let me know if there's anything else.

**Pull request merged**
