### PR TITLE
Issues #151 and #148 resolved

### PR DESCRIPTION
**Pull request by dannytoomey**
Hi Witold,

Here's a pull request that resolves issues #151 and #148. 

I updated my forked repository's code to the latest commit on the devel branch, but GitHub indicates it can't automatically merge. I'm not sure why. Let me know if there's anything else I should change!

Best regards,

Danny Toomey

### CODE REVIEW

**Comment by dannytoomey** [comment]
Found a small error after rebasing, currently fixing and will add a new commit with fix.

**Comment by dannytoomey** [comment]
Sorry for the useless commits here. I wanted to set up codecov and pushed it to this branch rather than a new one, then accidentally reverted my revert of the commit so had to do another one to fix things. Messy way to change nothing at all!

**Comment by dannytoomey** [comment]
Sorry for the force push here. I was messing with codecov and accidentally pushed a commit on this branch I meant to make on another one, so I reset this branch to the correct commit.

**Comment by wwiecek** [comment]
@dannytoomey same problem as in other PR, you created a large .so file. Can you delete this PR and start a fresh one to `devel` where you don't commit .so? I don't want to have that file anywhere in the history because it increases size of the repo many times

**Review by wwiecek — CHANGES_REQUESTED** [review]
Kill this commit and do one without .so file

**Comment by dannytoomey** [comment]
Misread your initial comment, I will close this PR and open a new one without any commits including the .so files

**Pull request closed without merging**
